name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          check-latest: true
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'

      - run: npx changelogithub # or changelogithub@0.12 if ensure the stable result
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Extract tag name
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          if [[ "$TAG_NAME" == *"-beta"* ]]; then
            echo "NPM_TAG=beta" >> $GITHUB_ENV
          elif [[ "$TAG_NAME" == *"-alpha"* ]]; then
            echo "NPM_TAG=alpha" >> $GITHUB_ENV
          else
            echo "NPM_TAG=latest" >> $GITHUB_ENV
          fi

      - name: Install dependencies
        run: pnpm -r install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        run: pnpm -r publish --access public --no-git-checks --tag ${{ env.NPM_TAG }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      # TODO: Notify on slack
